import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import NextAuthSessionProvider from "./providers/session-provider";
import { Toaster, toast } from 'sonner'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-neutral-900`}>
      
            <NextAuthSessionProvider>
            <Toaster />
            {children}
            </NextAuthSessionProvider>
         
        </body>
    </html>
  );
}
